// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjwqyevuyysdvgbxykqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impqd3F5ZXZ1eXlzZHZnYnh5a3FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MjMwMjksImV4cCI6MjA2MzA5OTAyOX0.6vg8Awbg7WNaZH6Stl6qNPLH5HCIMnjJbqtMPUslfy4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);